/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.itis.model.jooq.schema.Keys;
import ru.itis.model.jooq.schema.Public;
import ru.itis.model.jooq.schema.tables.records.ListenerRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Listener extends TableImpl<ListenerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.listener</code>
     */
    public static final Listener LISTENER_ENTITY = new Listener();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ListenerRecord> getRecordType() {
        return ListenerRecord.class;
    }

    /**
     * The column <code>public.listener.id</code>.
     */
    public final TableField<ListenerRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.listener.name</code>.
     */
    public final TableField<ListenerRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.listener.age</code>.
     */
    public final TableField<ListenerRecord, Integer> AGE = createField(DSL.name("age"), SQLDataType.INTEGER, this, "");

    private Listener(Name alias, Table<ListenerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Listener(Name alias, Table<ListenerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.listener</code> table reference
     */
    public Listener(String alias) {
        this(DSL.name(alias), LISTENER_ENTITY);
    }

    /**
     * Create an aliased <code>public.listener</code> table reference
     */
    public Listener(Name alias) {
        this(alias, LISTENER_ENTITY);
    }

    /**
     * Create a <code>public.listener</code> table reference
     */
    public Listener() {
        this(DSL.name("listener"), null);
    }

    public <O extends Record> Listener(Table<O> child, ForeignKey<O, ListenerRecord> key) {
        super(child, key, LISTENER_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ListenerRecord> getPrimaryKey() {
        return Keys.LISTENER_PK;
    }

    @Override
    public List<UniqueKey<ListenerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.LISTENER_NAME_UNIQUE_CONSTRAINT);
    }

    @Override
    public Listener as(String alias) {
        return new Listener(DSL.name(alias), this);
    }

    @Override
    public Listener as(Name alias) {
        return new Listener(alias, this);
    }

    @Override
    public Listener as(Table<?> alias) {
        return new Listener(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Listener rename(String name) {
        return new Listener(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Listener rename(Name name) {
        return new Listener(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Listener rename(Table<?> name) {
        return new Listener(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
