/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.itis.model.jooq.schema.Keys;
import ru.itis.model.jooq.schema.Public;
import ru.itis.model.jooq.schema.tables.records.MusicRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Music extends TableImpl<MusicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.music</code>
     */
    public static final Music MUSIC_ENTITY = new Music();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MusicRecord> getRecordType() {
        return MusicRecord.class;
    }

    /**
     * The column <code>public.music.id</code>.
     */
    public final TableField<MusicRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.music.name</code>.
     */
    public final TableField<MusicRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.music.storage_name</code>.
     */
    public final TableField<MusicRecord, String> STORAGE_NAME = createField(DSL.name("storage_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.music.author_id</code>.
     */
    public final TableField<MusicRecord, UUID> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.UUID, this, "");

    private Music(Name alias, Table<MusicRecord> aliased) {
        this(alias, aliased, null);
    }

    private Music(Name alias, Table<MusicRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.music</code> table reference
     */
    public Music(String alias) {
        this(DSL.name(alias), MUSIC_ENTITY);
    }

    /**
     * Create an aliased <code>public.music</code> table reference
     */
    public Music(Name alias) {
        this(alias, MUSIC_ENTITY);
    }

    /**
     * Create a <code>public.music</code> table reference
     */
    public Music() {
        this(DSL.name("music"), null);
    }

    public <O extends Record> Music(Table<O> child, ForeignKey<O, MusicRecord> key) {
        super(child, key, MUSIC_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MusicRecord> getPrimaryKey() {
        return Keys.MUSIC_PK;
    }

    @Override
    public List<UniqueKey<MusicRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MUSIC_NAME_UNIQUE_CONSTRAINT);
    }

    @Override
    public List<ForeignKey<MusicRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MUSIC__MUSIC_AUTHORID_FOREIGNKEY_CONSTRAINT);
    }

    private transient Author _author;

    /**
     * Get the implicit join path to the <code>public.author</code> table.
     */
    public Author author() {
        if (_author == null)
            _author = new Author(this, Keys.MUSIC__MUSIC_AUTHORID_FOREIGNKEY_CONSTRAINT);

        return _author;
    }

    @Override
    public Music as(String alias) {
        return new Music(DSL.name(alias), this);
    }

    @Override
    public Music as(Name alias) {
        return new Music(alias, this);
    }

    @Override
    public Music as(Table<?> alias) {
        return new Music(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Music rename(String name) {
        return new Music(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Music rename(Name name) {
        return new Music(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Music rename(Table<?> name) {
        return new Music(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, String, UUID> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super UUID, ? super String, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super UUID, ? super String, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
