/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import ru.itis.model.Entity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private Integer age;
    private UUID managerId;

    public AuthorEntity() {}

    public AuthorEntity(AuthorEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.managerId = value.managerId;
    }

    public AuthorEntity(
        UUID id,
        String name,
        Integer age,
        UUID managerId
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.managerId = managerId;
    }

    /**
     * Getter for <code>public.author.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.author.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.author.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.author.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.author.age</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>public.author.age</code>.
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Getter for <code>public.author.manager_id</code>.
     */
    public UUID getManagerId() {
        return this.managerId;
    }

    /**
     * Setter for <code>public.author.manager_id</code>.
     */
    public void setManagerId(UUID managerId) {
        this.managerId = managerId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AuthorEntity other = (AuthorEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.age == null) {
            if (other.age != null)
                return false;
        }
        else if (!this.age.equals(other.age))
            return false;
        if (this.managerId == null) {
            if (other.managerId != null)
                return false;
        }
        else if (!this.managerId.equals(other.managerId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        result = prime * result + ((this.managerId == null) ? 0 : this.managerId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthorEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(managerId);

        sb.append(")");
        return sb.toString();
    }
}
