/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import ru.itis.model.Entity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManagerEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private UUID authorId;
    private Integer age;

    public ManagerEntity() {}

    public ManagerEntity(ManagerEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.authorId = value.authorId;
        this.age = value.age;
    }

    public ManagerEntity(
        UUID id,
        String name,
        UUID authorId,
        Integer age
    ) {
        this.id = id;
        this.name = name;
        this.authorId = authorId;
        this.age = age;
    }

    /**
     * Getter for <code>public.manager.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.manager.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.manager.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.manager.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.manager.author_id</code>.
     */
    public UUID getAuthorId() {
        return this.authorId;
    }

    /**
     * Setter for <code>public.manager.author_id</code>.
     */
    public void setAuthorId(UUID authorId) {
        this.authorId = authorId;
    }

    /**
     * Getter for <code>public.manager.age</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>public.manager.age</code>.
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ManagerEntity other = (ManagerEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!this.authorId.equals(other.authorId))
            return false;
        if (this.age == null) {
            if (other.age != null)
                return false;
        }
        else if (!this.age.equals(other.age))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ManagerEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(authorId);
        sb.append(", ").append(age);

        sb.append(")");
        return sb.toString();
    }
}
