/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema;


import ru.itis.model.jooq.schema.tables.Account;
import ru.itis.model.jooq.schema.tables.AssociativeListenerMusic;
import ru.itis.model.jooq.schema.tables.Author;
import ru.itis.model.jooq.schema.tables.Listener;
import ru.itis.model.jooq.schema.tables.Manager;
import ru.itis.model.jooq.schema.tables.Music;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT_ENTITY = Account.ACCOUNT_ENTITY;

    /**
     * The table <code>public.associative_listener_music</code>.
     */
    public static final AssociativeListenerMusic ASSOCIATIVE_LISTENER_MUSIC_ENTITY = AssociativeListenerMusic.ASSOCIATIVE_LISTENER_MUSIC_ENTITY;

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR_ENTITY = Author.AUTHOR_ENTITY;

    /**
     * The table <code>public.listener</code>.
     */
    public static final Listener LISTENER_ENTITY = Listener.LISTENER_ENTITY;

    /**
     * The table <code>public.manager</code>.
     */
    public static final Manager MANAGER_ENTITY = Manager.MANAGER_ENTITY;

    /**
     * The table <code>public.music</code>.
     */
    public static final Music MUSIC_ENTITY = Music.MUSIC_ENTITY;
}
