/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.itis.model.jooq.schema.tables.Author;
import ru.itis.model.jooq.schema.tables.pojos.AuthorEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorRecord extends UpdatableRecordImpl<AuthorRecord> implements Record4<UUID, String, Integer, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.author.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.author.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.author.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.author.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.author.age</code>.
     */
    public void setAge(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.author.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.author.manager_id</code>.
     */
    public void setManagerId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.author.manager_id</code>.
     */
    public UUID getManagerId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, Integer, UUID> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, String, Integer, UUID> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Author.AUTHOR_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Author.AUTHOR_ENTITY.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Author.AUTHOR_ENTITY.AGE;
    }

    @Override
    public Field<UUID> field4() {
        return Author.AUTHOR_ENTITY.MANAGER_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getAge();
    }

    @Override
    public UUID component4() {
        return getManagerId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getAge();
    }

    @Override
    public UUID value4() {
        return getManagerId();
    }

    @Override
    public AuthorRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public AuthorRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AuthorRecord value3(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public AuthorRecord value4(UUID value) {
        setManagerId(value);
        return this;
    }

    @Override
    public AuthorRecord values(UUID value1, String value2, Integer value3, UUID value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorRecord
     */
    public AuthorRecord() {
        super(Author.AUTHOR_ENTITY);
    }

    /**
     * Create a detached, initialised AuthorRecord
     */
    public AuthorRecord(UUID id, String name, Integer age, UUID managerId) {
        super(Author.AUTHOR_ENTITY);

        setId(id);
        setName(name);
        setAge(age);
        setManagerId(managerId);
    }

    /**
     * Create a detached, initialised AuthorRecord
     */
    public AuthorRecord(AuthorEntity value) {
        super(Author.AUTHOR_ENTITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setAge(value.getAge());
            setManagerId(value.getManagerId());
        }
    }
}
