/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.itis.model.jooq.schema.tables.Listener;
import ru.itis.model.jooq.schema.tables.pojos.ListenerEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListenerRecord extends UpdatableRecordImpl<ListenerRecord> implements Record3<UUID, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.listener.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.listener.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.listener.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.listener.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.listener.age</code>.
     */
    public void setAge(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.listener.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Listener.LISTENER_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Listener.LISTENER_ENTITY.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Listener.LISTENER_ENTITY.AGE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getAge();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getAge();
    }

    @Override
    public ListenerRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ListenerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ListenerRecord value3(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public ListenerRecord values(UUID value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListenerRecord
     */
    public ListenerRecord() {
        super(Listener.LISTENER_ENTITY);
    }

    /**
     * Create a detached, initialised ListenerRecord
     */
    public ListenerRecord(UUID id, String name, Integer age) {
        super(Listener.LISTENER_ENTITY);

        setId(id);
        setName(name);
        setAge(age);
    }

    /**
     * Create a detached, initialised ListenerRecord
     */
    public ListenerRecord(ListenerEntity value) {
        super(Listener.LISTENER_ENTITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setAge(value.getAge());
        }
    }
}
