/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.itis.model.jooq.schema.tables.Manager;
import ru.itis.model.jooq.schema.tables.pojos.ManagerEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManagerRecord extends UpdatableRecordImpl<ManagerRecord> implements Record4<UUID, String, UUID, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.manager.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.manager.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.manager.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.manager.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.manager.author_id</code>.
     */
    public void setAuthorId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.manager.author_id</code>.
     */
    public UUID getAuthorId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.manager.age</code>.
     */
    public void setAge(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.manager.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, UUID, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, String, UUID, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Manager.MANAGER_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Manager.MANAGER_ENTITY.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return Manager.MANAGER_ENTITY.AUTHOR_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Manager.MANAGER_ENTITY.AGE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getAuthorId();
    }

    @Override
    public Integer component4() {
        return getAge();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getAuthorId();
    }

    @Override
    public Integer value4() {
        return getAge();
    }

    @Override
    public ManagerRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ManagerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ManagerRecord value3(UUID value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public ManagerRecord value4(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public ManagerRecord values(UUID value1, String value2, UUID value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManagerRecord
     */
    public ManagerRecord() {
        super(Manager.MANAGER_ENTITY);
    }

    /**
     * Create a detached, initialised ManagerRecord
     */
    public ManagerRecord(UUID id, String name, UUID authorId, Integer age) {
        super(Manager.MANAGER_ENTITY);

        setId(id);
        setName(name);
        setAuthorId(authorId);
        setAge(age);
    }

    /**
     * Create a detached, initialised ManagerRecord
     */
    public ManagerRecord(ManagerEntity value) {
        super(Manager.MANAGER_ENTITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setAuthorId(value.getAuthorId());
            setAge(value.getAge());
        }
    }
}
